name: Black Format

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip install pipenv && pipenv install --dev

      - name: Run Black
        run: pipenv run black .
